apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /mnt/main
      name: volume
  volumes:
  - name: volume
    hostPath:
      path: /Users/ajaykumar/kube/
