apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-01
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: Pod
apiVersion: v1
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - mountPath: "/usr/share/nginx/html/"
        name: nginx-vol
  volumes:
    - name: nginx-vol
      persistentVolumeClaim:
        claimName: pv-01
