apiVersion: v1
kind: PersistentVolume
metadata:
  name: test
  namespace: ajay
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual    #manual, slow, standard etc
  
  
  ---
  
