
apiVersion: v1
kind: ConfigMap

metadata:
    name: configmap
    labels:
        app: nginx   
data:
    index.html: |
        "hello  world. Config map testing 1   2   3"
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
      env:
        
        - name: html-file
          valueFrom:
            configMapKeyRef:
              name: html-file
              key: special.how
