---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: dXMtZWFzdC0x
  AWS_SECRET_ACCESS_KEY: QUtJQUlLM1paNTdHVVkyUEszNUE=
  AWS_DEFAULT_REGION: bGJhSFNmU0hkODEva1BnSTFFa3FUOUF6Q2kzSlBLMFJpaEFPWTFuOA==
  
---
apiVersion: v1
kind: Pod
metadata:
  name: awscli
spec:
  containers:
  - name: awscli
    image: organs/awscli
  - env:
      - name: Keys
        valueFrom:
          secretKeyRef:
            key: AWS_ACCESS_KEY_ID
            name: AWS_ACCESS_KEY_ID
            key: AWS_SECRET_ACCESS_KEY
            name: AWS_SECRET_ACCESS_KEY
            key: AWS_DEFAULT_REGION
            name: AWS_DEFAULT_REGION
   args:
            - /bin/sh
            - -c
            aws s3 ls;
      
