---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQUlLM1paxxxNTdHVVkyUEszNUE=
  AWS_SECRET_ACCESS_KEY: xxxxxx
  AWS_DEFAULT_REGION: dXMtZWFzdxxxC0x
  
---
apiVersion: v1
kind: Pod
metadata:
  name: awscli
spec:
  containers:
  - env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY_ID
              name: mysecret
              optional: false
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              key: AWS_DEFAULT_REGION
              name: mysecret
              optional: false
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: mysecret
              optional: false
    image: organs/awscli
    name: awscli
    command: ["bin/sh", "-c", "aws s3 ls"]
